package postest3;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus
 */
public class tugas2 extends javax.swing.JFrame {

    /**
     * Creates new form Border
     */
    public tugas2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JP = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Base = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Heroes = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Capture = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Maps = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        About = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        JPP = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        Home = new javax.swing.JButton();
        Hero = new javax.swing.JButton();
        Gal = new javax.swing.JButton();
        Mps = new javax.swing.JButton();
        Bout = new javax.swing.JButton();
        Logo = new javax.swing.JLabel();
        CP = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        JP.setBackground(new java.awt.Color(255, 153, 153));
        JP.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.CardLayout());

        Base.setBackground(new java.awt.Color(102, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/postest3/cover.png"))); // NOI18N

        javax.swing.GroupLayout BaseLayout = new javax.swing.GroupLayout(Base);
        Base.setLayout(BaseLayout);
        BaseLayout.setHorizontalGroup(
            BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BaseLayout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        BaseLayout.setVerticalGroup(
            BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BaseLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(23, 23, 23))
        );

        jPanel2.add(Base, "card2");

        Heroes.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/postest3/TI7IfY8.png"))); // NOI18N

        javax.swing.GroupLayout HeroesLayout = new javax.swing.GroupLayout(Heroes);
        Heroes.setLayout(HeroesLayout);
        HeroesLayout.setHorizontalGroup(
            HeroesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeroesLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel4)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        HeroesLayout.setVerticalGroup(
            HeroesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeroesLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jLabel4)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        jPanel2.add(Heroes, "card3");

        Capture.setBackground(new java.awt.Color(0, 0, 0));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/postest3/54184b4c5613f.jpg"))); // NOI18N
        jLabel6.setText("Glbertzy");

        javax.swing.GroupLayout CaptureLayout = new javax.swing.GroupLayout(Capture);
        Capture.setLayout(CaptureLayout);
        CaptureLayout.setHorizontalGroup(
            CaptureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CaptureLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel6)
                .addContainerGap(273, Short.MAX_VALUE))
        );
        CaptureLayout.setVerticalGroup(
            CaptureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CaptureLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel2.add(Capture, "card4");

        Maps.setBackground(new java.awt.Color(0, 153, 51));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/postest3/Hero-Icons.jpg"))); // NOI18N
        jLabel5.setText("Maps");

        javax.swing.GroupLayout MapsLayout = new javax.swing.GroupLayout(Maps);
        Maps.setLayout(MapsLayout);
        MapsLayout.setHorizontalGroup(
            MapsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MapsLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel5)
                .addContainerGap(141, Short.MAX_VALUE))
        );
        MapsLayout.setVerticalGroup(
            MapsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MapsLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel5)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jPanel2.add(Maps, "card5");

        About.setBackground(new java.awt.Color(0, 0, 153));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/postest3/abaddon-dota-2-face-5.jpg"))); // NOI18N
        jLabel9.setText("Glbertzy");

        javax.swing.GroupLayout AboutLayout = new javax.swing.GroupLayout(About);
        About.setLayout(AboutLayout);
        AboutLayout.setHorizontalGroup(
            AboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboutLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel9)
                .addContainerGap(160, Short.MAX_VALUE))
        );
        AboutLayout.setVerticalGroup(
            AboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboutLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel9)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel2.add(About, "card6");

        JP.add(jPanel2, java.awt.BorderLayout.CENTER);

        JPP.setBackground(new java.awt.Color(0, 102, 255));

        jLabel2.setFont(new java.awt.Font("Sitka Banner", 1, 36)); // NOI18N
        jLabel2.setText("Leaderboard MMR DOTA 2");

        jLabel3.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        jLabel3.setText("Top 100 MMR World Wide");

        jPanel5.setLayout(new java.awt.GridLayout(1, 0, 15, 0));

        Home.setText("HOME ");
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        jPanel5.add(Home);

        Hero.setText("HEROES");
        Hero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HeroActionPerformed(evt);
            }
        });
        jPanel5.add(Hero);

        Gal.setText("GALLERY");
        Gal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GalActionPerformed(evt);
            }
        });
        jPanel5.add(Gal);

        Mps.setText("MAPS");
        Mps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MpsActionPerformed(evt);
            }
        });
        jPanel5.add(Mps);

        Bout.setText("ABOUT");
        Bout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutActionPerformed(evt);
            }
        });
        jPanel5.add(Bout);

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/postest3/dota-2-logo-blue-wallpaper-1.jpg"))); // NOI18N
        Logo.setText("jLabel8");

        javax.swing.GroupLayout JPPLayout = new javax.swing.GroupLayout(JPP);
        JPP.setLayout(JPPLayout);
        JPPLayout.setHorizontalGroup(
            JPPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPPLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPPLayout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        JPPLayout.setVerticalGroup(
            JPPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPPLayout.createSequentialGroup()
                .addGroup(JPPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPPLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addGroup(JPPLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(Logo)))
                .addGap(75, 75, 75)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JP.add(JPP, java.awt.BorderLayout.PAGE_START);

        CP.setBackground(new java.awt.Color(0, 153, 255));

        jLabel7.setText("copyright@A2015");

        javax.swing.GroupLayout CPLayout = new javax.swing.GroupLayout(CP);
        CP.setLayout(CPLayout);
        CPLayout.setHorizontalGroup(
            CPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CPLayout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(jLabel7)
                .addContainerGap(274, Short.MAX_VALUE))
        );
        CPLayout.setVerticalGroup(
            CPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CPLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel7)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        JP.add(CP, java.awt.BorderLayout.PAGE_END);

        jMenu1.setText("DATA");

        jMenuItem1.setText("Input Heroes");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Cari Data");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Data Heroes");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("LAPORAN");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("EXIT");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(JP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        // TODO add your handling code here:
        Base.setVisible(true);
        Heroes. setVisible(false);
        Capture.setVisible(false);
        Maps.setVisible(false);
        About.setVisible(false);
    }//GEN-LAST:event_HomeActionPerformed

    private void HeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HeroActionPerformed
        // TODO add your handling code here:
         Base.setVisible(false);
        Heroes. setVisible(true);
        Capture.setVisible(false);
        Maps.setVisible(false);
        About.setVisible(false);
    }//GEN-LAST:event_HeroActionPerformed

    private void GalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GalActionPerformed
        // TODO add your handling code here:
         Base.setVisible(false);
        Heroes. setVisible(false);
        Capture.setVisible(true);
        Maps.setVisible(false);
        About.setVisible(false);
    }//GEN-LAST:event_GalActionPerformed

    private void MpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MpsActionPerformed
        // TODO add your handling code here:
         Base.setVisible(false);
        Heroes. setVisible(false);
        Capture.setVisible(false);
        Maps.setVisible(true);
        About.setVisible(false);
    }//GEN-LAST:event_MpsActionPerformed

    private void BoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutActionPerformed
        // TODO add your handling code here:
         Base.setVisible(false);
        Heroes. setVisible(false);
        Capture.setVisible(false);
        Maps.setVisible(false);
        About.setVisible(true);
    }//GEN-LAST:event_BoutActionPerformed

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenu3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tugas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tugas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tugas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tugas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tugas2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel About;
    private javax.swing.JPanel Base;
    private javax.swing.JButton Bout;
    private javax.swing.JPanel CP;
    private javax.swing.JPanel Capture;
    private javax.swing.JButton Gal;
    private javax.swing.JButton Hero;
    private javax.swing.JPanel Heroes;
    private javax.swing.JButton Home;
    private javax.swing.JPanel JP;
    private javax.swing.JPanel JPP;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel Maps;
    private javax.swing.JButton Mps;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
